language: go

go:
  - 1.13.x
  - 1.14.x

git:
  depth: 1

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install:

notifications:
  email: false

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

script:
  - make build test lint
