// Copyright © 2015-2018 Victor Antonovich <victor@antonovich.me>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "go:generate go run cmd/gendeps/main.go". DO NOT EDIT.

package main

import (
	"fmt"

	corev1 "k8s.io/api/core/v1"
)

func (dm *DependencyManager) Pods(namespace, selector string) ([]corev1.Pod, error) {
	key := fmt.Sprintf("pods(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.Pod), nil
	}
	pods, err := dm.client.Pods(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, pods)
	return pods, nil
}

func (dm *DependencyManager) Services(namespace, selector string) ([]corev1.Service, error) {
	key := fmt.Sprintf("services(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.Service), nil
	}
	services, err := dm.client.Services(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, services)
	return services, nil
}

func (dm *DependencyManager) ReplicationControllers(namespace, selector string) ([]corev1.ReplicationController, error) {
	key := fmt.Sprintf("replicationcontrollers(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.ReplicationController), nil
	}
	replicationcontrollers, err := dm.client.ReplicationControllers(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, replicationcontrollers)
	return replicationcontrollers, nil
}

func (dm *DependencyManager) Events(namespace, selector string) ([]corev1.Event, error) {
	key := fmt.Sprintf("events(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.Event), nil
	}
	events, err := dm.client.Events(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, events)
	return events, nil
}

func (dm *DependencyManager) Endpoints(namespace, selector string) ([]corev1.Endpoints, error) {
	key := fmt.Sprintf("endpoints(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.Endpoints), nil
	}
	endpoints, err := dm.client.Endpoints(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, endpoints)
	return endpoints, nil
}

func (dm *DependencyManager) Nodes(selector string) ([]corev1.Node, error) {
	key := fmt.Sprintf("nodes(%s)", selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.Node), nil
	}
	nodes, err := dm.client.Nodes(selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, nodes)
	return nodes, nil
}

func (dm *DependencyManager) Namespaces(selector string) ([]corev1.Namespace, error) {
	key := fmt.Sprintf("namespaces(%s)", selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.Namespace), nil
	}
	namespaces, err := dm.client.Namespaces(selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, namespaces)
	return namespaces, nil
}

func (dm *DependencyManager) ComponentStatuses(selector string) ([]corev1.ComponentStatus, error) {
	key := fmt.Sprintf("componentstatuses(%s)", selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.ComponentStatus), nil
	}
	componentstatuses, err := dm.client.ComponentStatuses(selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, componentstatuses)
	return componentstatuses, nil
}

func (dm *DependencyManager) ConfigMaps(namespace, selector string) ([]corev1.ConfigMap, error) {
	key := fmt.Sprintf("configmaps(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.ConfigMap), nil
	}
	configmaps, err := dm.client.ConfigMaps(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, configmaps)
	return configmaps, nil
}

func (dm *DependencyManager) LimitRanges(namespace, selector string) ([]corev1.LimitRange, error) {
	key := fmt.Sprintf("limitranges(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.LimitRange), nil
	}
	limitranges, err := dm.client.LimitRanges(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, limitranges)
	return limitranges, nil
}

func (dm *DependencyManager) PersistentVolumes(selector string) ([]corev1.PersistentVolume, error) {
	key := fmt.Sprintf("persistentvolumes(%s)", selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.PersistentVolume), nil
	}
	persistentvolumes, err := dm.client.PersistentVolumes(selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, persistentvolumes)
	return persistentvolumes, nil
}

func (dm *DependencyManager) PersistentVolumeClaims(namespace, selector string) ([]corev1.PersistentVolumeClaim, error) {
	key := fmt.Sprintf("persistentvolumeclaims(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.PersistentVolumeClaim), nil
	}
	persistentvolumeclaims, err := dm.client.PersistentVolumeClaims(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, persistentvolumeclaims)
	return persistentvolumeclaims, nil
}

func (dm *DependencyManager) PodTemplates(namespace, selector string) ([]corev1.PodTemplate, error) {
	key := fmt.Sprintf("podtemplates(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.PodTemplate), nil
	}
	podtemplates, err := dm.client.PodTemplates(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, podtemplates)
	return podtemplates, nil
}

func (dm *DependencyManager) ResourceQuotas(namespace, selector string) ([]corev1.ResourceQuota, error) {
	key := fmt.Sprintf("resourcequotas(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.ResourceQuota), nil
	}
	resourcequotas, err := dm.client.ResourceQuotas(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, resourcequotas)
	return resourcequotas, nil
}

func (dm *DependencyManager) Secrets(namespace, selector string) ([]corev1.Secret, error) {
	key := fmt.Sprintf("secrets(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.Secret), nil
	}
	secrets, err := dm.client.Secrets(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, secrets)
	return secrets, nil
}

func (dm *DependencyManager) ServiceAccounts(namespace, selector string) ([]corev1.ServiceAccount, error) {
	key := fmt.Sprintf("serviceaccounts(%s,%s)", namespace, selector)
	if value, found := dm.cachedDependency(key); found {
		return value.([]corev1.ServiceAccount), nil
	}
	serviceaccounts, err := dm.client.ServiceAccounts(namespace, selector)
	if err != nil {
		return nil, err
	}
	dm.cacheDependency(key, serviceaccounts)
	return serviceaccounts, nil
}
